AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  tellegramnewsbotv1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::296324052001:role/service-role/tellegram_news_bot_v1-role-o2nsl217
      Layers:
        - 'arn:aws:lambda:ap-northeast-2:296324052001:layer:exlib:1'
      RuntimePolicy:
        UpdateRuntimeOn: Auto
